// src/utils/hexagramData.ts
// 键名格式：从下往上的六爻（0=阴, 1=阳）

export interface Hexagram {
  nameZh: string;
  nameEn: string;
  poemZh: string;
}

export const HEXAGRAM_MAP: Record<string, Hexagram> = {
  "111111": { nameZh: "乾", nameEn: "The Creative", poemZh: "天行健，君子以自强不息。" },
  "000000": { nameZh: "坤", nameEn: "The Receptive", poemZh: "地势坤，君子以厚德载物。" },
  "010001": { nameZh: "屯", nameEn: "Difficulty at the Beginning", poemZh: "云雷，屯。君子以经纶。" },
  "100010": { nameZh: "蒙", nameEn: "Youthful Folly", poemZh: "山下出泉，蒙。君子以果行育德。" },
  "111010": { nameZh: "需", nameEn: "Waiting", poemZh: "云上于天，需。君子以饮食宴乐。" },
  "010111": { nameZh: "讼", nameEn: "Conflict", poemZh: "天与水违行，讼。君子以作事谋始。" },
  "010000": { nameZh: "师", nameEn: "The Army", poemZh: "地中有水，师。君子以容民畜众。" },
  "000010": { nameZh: "比", nameEn: "Holding Together", poemZh: "地上有水，比。先王以建万国，亲诸侯。" },
  "111011": { nameZh: "小畜", nameEn: "Small Taming", poemZh: "风行天上，小畜。君子以懿文德。" },
  "110111": { nameZh: "履", nameEn: "Treading", poemZh: "上天下泽，履。君子以辨上下，安民志。" },
  "111000": { nameZh: "泰", nameEn: "Peace", poemZh: "天地交，泰。后以财成天地之道。" },
  "000111": { nameZh: "否", nameEn: "Standstill", poemZh: "天地不交，否。君子以俭德辟难。" },
  "101111": { nameZh: "同人", nameEn: "Fellowship", poemZh: "天与火，同人。君子以类族辨物。" },
  "111101": { nameZh: "大有", nameEn: "Possession in Great Measure", poemZh: "火在天上，大有。君子以遏恶扬善。" },
  "000100": { nameZh: "谦", nameEn: "Modesty", poemZh: "地中有山，谦。君子以裒多益寡。" },
  "001000": { nameZh: "豫", nameEn: "Enthusiasm", poemZh: "雷出地奋，豫。先王以作乐崇德。" },
  "100110": { nameZh: "随", nameEn: "Following", poemZh: "泽中有雷，随。君子以向晦入宴息。" },
  "011001": { nameZh: "蛊", nameEn: "Work on the Decayed", poemZh: "山下有风，蛊。君子以振民育德。" },
  "110000": { nameZh: "临", nameEn: "Approach", poemZh: "泽上有地，临。君子以教思无穷。" },
  "000011": { nameZh: "观", nameEn: "Contemplation", poemZh: "风行地上，观。先王以省方观民设教。" },
  "100101": { nameZh: "噬嗑", nameEn: "Biting Through", poemZh: "雷电，噬嗑。先王以明罚敕法。" },
  "101001": { nameZh: "贲", nameEn: "Grace", poemZh: "山下有火，贲。君子以明庶政，无敢断狱。" },
  "000001": { nameZh: "剥", nameEn: "Splitting Apart", poemZh: "山附于地，剥。上以厚下，安宅。" },
  "100000": { nameZh: "复", nameEn: "Return", poemZh: "地中有雷，复。先王以至日闭关。" },
  "100111": { nameZh: "无妄", nameEn: "Innocence", poemZh: "天下雷行，无妄。先王以茂对时育万物。" },
  "111001": { nameZh: "大畜", nameEn: "Great Taming", poemZh: "山天大畜。君子以多识前言往行。" },
  "100001": { nameZh: "颐", nameEn: "Corners of the Mouth", poemZh: "山下有雷，颐。君子以慎言语，节饮食。" },
  "011110": { nameZh: "大过", nameEn: "Preponderance of the Great", poemZh: "泽灭木，大过。君子以独立不惧。" },
  "010010": { nameZh: "坎", nameEn: "The Abysmal", poemZh: "水洊至，习坎。君子以常德行，习教事。" },
  "101101": { nameZh: "离", nameEn: "The Clinging", poemZh: "明两作，离。大人以继明照于四方。" },
  "001110": { nameZh: "咸", nameEn: "Influence", poemZh: "山上有泽，咸。君子以虚受人。" },
  "011100": { nameZh: "恒", nameEn: "Duration", poemZh: "雷风，恒。君子以立不易方。" },
  "001111": { nameZh: "遁", nameEn: "Retreat", poemZh: "天下有山，遁。君子以远小人，不恶而严。" },
  "111100": { nameZh: "大壮", nameEn: "Great Power", poemZh: "雷在天上，大壮。君子以非礼弗履。" },
  "000101": { nameZh: "晋", nameEn: "Progress", poemZh: "明出地上，晋。君子以自昭明德。" },
  "101000": { nameZh: "明夷", nameEn: "Darkening of the Light", poemZh: "明入地中，明夷。君子以莅众，用晦而明。" },
  "101011": { nameZh: "家人", nameEn: "The Family", poemZh: "风自火出，家人。君子以言有物而行有恒。" },
  "110101": { nameZh: "睽", nameEn: "Opposition", poemZh: "上火下泽，睽。君子以同而异。" },
  "001010": { nameZh: "蹇", nameEn: "Obstruction", poemZh: "山上有水，蹇。君子以反身修德。" },
  "010100": { nameZh: "解", nameEn: "Deliverance", poemZh: "雷雨作，解。君子以赦过宥罪。" },
  "110001": { nameZh: "损", nameEn: "Decrease", poemZh: "山下有泽，损。君子以惩忿窒欲。" },
  "100011": { nameZh: "益", nameEn: "Increase", poemZh: "风雷，益。君子以见善则迁，有过则改。" },
  "111110": { nameZh: "夬", nameEn: "Breakthrough", poemZh: "泽上于天，夬。君子以施禄及下，居德则忌。" },
  "011111": { nameZh: "姤", nameEn: "Coming to Meet", poemZh: "天下有风，姤。后以施命诰四方。" },
  "000110": { nameZh: "萃", nameEn: "Gathering Together", poemZh: "泽上于地，萃。君子以除戎器，戒不虞。" },
  "011000": { nameZh: "升", nameEn: "Pushing Upward", poemZh: "地中生木，升。君子以顺德，积小以高大。" },
  "010110": { nameZh: "困", nameEn: "Oppression", poemZh: "泽无水，困。君子以致命遂志。" },
  "011010": { nameZh: "井", nameEn: "The Well", poemZh: "木上有水，井。君子以劳民劝相。" },
  "101110": { nameZh: "革", nameEn: "Revolution", poemZh: "泽中有火，革。君子以治历明时。" },
  "011101": { nameZh: "鼎", nameEn: "The Caldron", poemZh: "木上有火，鼎。君子以正位凝命。" },
  "001001": { nameZh: "震", nameEn: "The Arousing", poemZh: "洊雷，震。君子以恐惧修省。" },
  "100100": { nameZh: "艮", nameEn: "Keeping Still", poemZh: "兼山，艮。君子以思不出其位。" },
  "001011": { nameZh: "渐", nameEn: "Development", poemZh: "山上有木，渐。君子以居贤德善俗。" },
  "110100": { nameZh: "归妹", nameEn: "The Marrying Maiden", poemZh: "泽上有雷，归妹。君子以永终知敝。" },
  "101100": { nameZh: "丰", nameEn: "Abundance", poemZh: "雷电皆至，丰。君子以折狱致刑。" },
  "001101": { nameZh: "旅", nameEn: "The Wanderer", poemZh: "山上有火，旅。君子以明慎用刑，而不留狱。" },
  "011011": { nameZh: "巽", nameEn: "The Gentle", poemZh: "随风，巽。君子以申命行事。" },
  "110110": { nameZh: "兑", nameEn: "The Joyous", poemZh: "丽泽，兑。君子以朋友讲习。" },
  "010011": { nameZh: "涣", nameEn: "Dispersion", poemZh: "风行水上，涣。先王以享于帝立庙。" },
  "110010": { nameZh: "节", nameEn: "Limitation", poemZh: "泽上有水，节。君子以制数度，议德行。" },
  "110011": { nameZh: "中孚", nameEn: "Inner Truth", poemZh: "泽上有风，中孚。君子以议狱缓死。" },
  "001100": { nameZh: "小过", nameEn: "Preponderance of the Small", poemZh: "山上有雷，小过。君子以行过乎恭，丧过乎哀。" },
  "101010": { nameZh: "既济", nameEn: "After Completion", poemZh: "水在火上，既济。君子以思患而预防之。" },
  "010101": { nameZh: "未济", nameEn: "Before Completion", poemZh: "火在水上，未济。君子以慎辨物居方。" }
};